service: tareas-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    TABLA_TAREAS: TareasTable
    COLATAREAS_URL:
      Ref: ColaTareas
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            # - "dynamodb:Scan"
            - "dynamodb:Query"
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [TareasTable, Arn]
            - Fn::GetAtt: [ColaTareas, Arn]

functions:
  crearTarea:
    handler: src/handlers/crearTarea.crearTarea
    events:
      - httpApi:
          path: /tareas
          method: post
  listarTareas:
    handler: src/handlers/listarTareas.listarTareas
    events:
      - httpApi:
          path: /tareas
          method: get
  procesarTarea:
    handler: src/handlers/procesarTarea.procesarTarea
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ColaTareas
              - Arn

resources:
  Resources:
    TareasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TareasTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: usuario
            AttributeType: S
          - AttributeName: fecha_id
            AttributeType: S
        KeySchema:
          - AttributeName: usuario
            KeyType: HASH
          - AttributeName: fecha_id
            KeyType: RANGE
    ColaTareas:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ColaTareas